# Generated by Django 3.0.6 on 2020-05-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updadted',
            new_name='updated',
        ),
    ]
